In [1]:
#model: using the FinancialBERT model, which is fine-tuned on financial news data and suitable for my subject
from transformers import BertTokenizer, BertForSequenceClassification
from transformers import pipeline
import transformers
import pandas as pd
import numpy as np

d:\self-definedEnvrionments\pytorch_test\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
print(transformers.__version__)

4.51.3

In [3]:
model = BertForSequenceClassification.from_pretrained("ahmedrachid/FinancialBERT-Sentiment-Analysis",num_labels=3)
tokenizer = BertTokenizer.from_pretrained("ahmedrachid/FinancialBERT-Sentiment-Analysis")

nlp = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)

Device set to use cpu

In [12]:
#import data
train = pd.read_csv(r"G:\Interview Projects\reddit\trainingdata.csv")
train

,id,title,selftext,author,created_utc,score,num_comments,url,subreddit,upvote_ratio,...,match_type,confidence,fiscalDateEnding,reportedDate,reportedEPS,estimatedEPS,surprise,surprisePercentage,window_start,window_end
0,npgy6l,Caught a glimpse of AMC on its way to the moon!!,NaN,TheMarkIII,2021-06-01 00:05:19+00:00,1,1.0,https://i.redd.it/tuw6d5qlpj271.jpg,wallstreetbets,1.00,...,exact_ticker,100,2021-07-31,2021-08-17,1.10,0.99,0.11,11.1111,2021-07-17,2021-08-16
1,nphcon,A pes M ake C ash! When this week is the quest...,NaN,ChuckLoner1980,2021-06-01 00:25:34+00:00,1,1.0,https://i.redd.it/3rg1kzm7tj271.jpg,wallstreetbets,1.00,...,exact_ticker,100,2021-07-31,2021-08-17,1.10,0.99,0.11,11.1111,2021-07-17,2021-08-16
2,nphgfq,$180k on Discovery DISCA - Holding Strong for ...,NaN,BeWithoutCause,2021-06-01 00:31:05+00:00,28,108.0,https://www.reddit.com/gallery/nphgfq,wallstreetbets,0.57,...,exact_ticker,100,2021-07-31,2021-08-17,1.10,0.99,0.11,11.1111,2021-07-17,2021-08-16
3,nphkm4,Shib is exploding right now. India unleashed c...,NaN,SellAndAvoidHell,2021-06-01 00:37:09+00:00,1,0.0,https://i.redd.it/iaf82iu9vj271.jpg,wallstreetbets,1.00,...,exact_ticker,100,2021-07-31,2021-08-17,1.10,0.99,0.11,11.1111,2021-07-17,2021-08-16
4,nphl4v,I kept checking the sub and listening to retar...,NaN,ksegur,2021-06-01 00:37:59+00:00,1,1.0,https://i.redd.it/k70kaz8fvj271.jpg,wallstreetbets,1.00,...,exact_ticker,100,2021-07-31,2021-08-17,1.10,0.99,0.11,11.1111,2021-07-17,2021-08-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45927,omvama,OPEC Deal is messing with me,"A very happy moment for us all, OPEC made a de...",wine_dine_and69,2021-07-18 17:38:31+00:00,72,96.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.87,...,exact_ticker,100,2021-06-30,2021-07-30,1.71,1.60,0.11,6.8750,2021-06-30,2021-07-29
45928,opvvdq,$UAA DD Earning 08/03/2021,Under Armour \n\nTicker Symbol: $UAA\n\nCurren...,Proof_Sand_8277,2021-07-23 05:37:42+00:00,10,26.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.66,...,exact_ticker,100,2021-06-30,2021-08-03,0.24,0.06,0.18,300.0000,2021-07-03,2021-08-02
45929,ot8wlv,Crying over your heavy $CRSR bags? Then this i...,"Alright retards, put down your peanutbutter an...",[deleted],2021-07-28 12:28:57+00:00,530,117.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.93,...,exact_ticker,100,2021-06-30,2021-08-05,2.07,1.92,0.15,7.8125,2021-07-05,2021-08-04
45930,p0s8nu,Forget FAANG introducing the THICC ASS portfolio,https://preview.redd.it/ijdtc42xr8g71.png?widt...,rocksblocks88,2021-08-09 02:17:36+00:00,397,61.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.93,...,exact_ticker,100,2021-07-31,2021-08-24,1.97,1.59,0.38,23.8994,2021-07-24,2021-08-23
45931,p5gb14,"$PAYA , payment processor with low IV","Hello, so I follow the [Kelly Criterion](https...",repos39,2021-08-16 13:42:04+00:00,553,216.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.97,...,exact_ticker,100,2021-07-31,2021-08-24,1.97,1.59,0.38,23.8994,2021-07-24,2021-08-23

In [ ]:
train[train['title'].isna()==False] #title has more valid data

,id,title,selftext,author,created_utc,score,num_comments,url,subreddit,upvote_ratio,...,match_type,confidence,fiscalDateEnding,reportedDate,reportedEPS,estimatedEPS,surprise,surprisePercentage,window_start,window_end
0,npgy6l,Caught a glimpse of AMC on its way to the moon!!,NaN,TheMarkIII,2021-06-01 00:05:19+00:00,1,1.0,https://i.redd.it/tuw6d5qlpj271.jpg,wallstreetbets,1.00,...,exact_ticker,100,2021-07-31,2021-08-17,1.10,0.99,0.11,11.1111,2021-07-17,2021-08-16
1,nphcon,A pes M ake C ash! When this week is the quest...,NaN,ChuckLoner1980,2021-06-01 00:25:34+00:00,1,1.0,https://i.redd.it/3rg1kzm7tj271.jpg,wallstreetbets,1.00,...,exact_ticker,100,2021-07-31,2021-08-17,1.10,0.99,0.11,11.1111,2021-07-17,2021-08-16
2,nphgfq,$180k on Discovery DISCA - Holding Strong for ...,NaN,BeWithoutCause,2021-06-01 00:31:05+00:00,28,108.0,https://www.reddit.com/gallery/nphgfq,wallstreetbets,0.57,...,exact_ticker,100,2021-07-31,2021-08-17,1.10,0.99,0.11,11.1111,2021-07-17,2021-08-16
3,nphkm4,Shib is exploding right now. India unleashed c...,NaN,SellAndAvoidHell,2021-06-01 00:37:09+00:00,1,0.0,https://i.redd.it/iaf82iu9vj271.jpg,wallstreetbets,1.00,...,exact_ticker,100,2021-07-31,2021-08-17,1.10,0.99,0.11,11.1111,2021-07-17,2021-08-16
4,nphl4v,I kept checking the sub and listening to retar...,NaN,ksegur,2021-06-01 00:37:59+00:00,1,1.0,https://i.redd.it/k70kaz8fvj271.jpg,wallstreetbets,1.00,...,exact_ticker,100,2021-07-31,2021-08-17,1.10,0.99,0.11,11.1111,2021-07-17,2021-08-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45927,omvama,OPEC Deal is messing with me,"A very happy moment for us all, OPEC made a de...",wine_dine_and69,2021-07-18 17:38:31+00:00,72,96.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.87,...,exact_ticker,100,2021-06-30,2021-07-30,1.71,1.60,0.11,6.8750,2021-06-30,2021-07-29
45928,opvvdq,$UAA DD Earning 08/03/2021,Under Armour \n\nTicker Symbol: $UAA\n\nCurren...,Proof_Sand_8277,2021-07-23 05:37:42+00:00,10,26.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.66,...,exact_ticker,100,2021-06-30,2021-08-03,0.24,0.06,0.18,300.0000,2021-07-03,2021-08-02
45929,ot8wlv,Crying over your heavy $CRSR bags? Then this i...,"Alright retards, put down your peanutbutter an...",[deleted],2021-07-28 12:28:57+00:00,530,117.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.93,...,exact_ticker,100,2021-06-30,2021-08-05,2.07,1.92,0.15,7.8125,2021-07-05,2021-08-04
45930,p0s8nu,Forget FAANG introducing the THICC ASS portfolio,https://preview.redd.it/ijdtc42xr8g71.png?widt...,rocksblocks88,2021-08-09 02:17:36+00:00,397,61.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.93,...,exact_ticker,100,2021-07-31,2021-08-24,1.97,1.59,0.38,23.8994,2021-07-24,2021-08-23
45931,p5gb14,"$PAYA , payment processor with low IV","Hello, so I follow the [Kelly Criterion](https...",repos39,2021-08-16 13:42:04+00:00,553,216.0,https://www.reddit.com/r/wallstreetbets/commen...,wallstreetbets,0.97,...,exact_ticker,100,2021-07-31,2021-08-24,1.97,1.59,0.38,23.8994,2021-07-24,2021-08-23

In [6]:
results = nlp(train['selftext'])
results

ValueError: text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).